# 这个工作流的核心目的是：定期自动扫描仓库中的所有 Issue 和 Pull Request（PR），如果发现有一段时间没有任何活动（即“不活跃”），就自动给它添加一个标签（如 Inactive）以示提醒，并可能会自动关闭它们。
name: Issue Check Inactive

on:
  schedule:
    - cron: '0 0 */15 * *'

permissions:
  contents: read

jobs:
  issue-check-inactive:
    permissions:
      issues: write # for actions-cool/issues-helper to update issues
      pull-requests: write # for actions-cool/issues-helper to update PRs
    runs-on: ubuntu-latest
    steps:
      - name: check-inactive
        uses: actions-cool/issues-helper@v3
        with:
          actions: check-inactive
          inactive-label: Inactive
          inactive-day: 30
