# 这个 GitHub Actions 脚本的目的是在 GitHub 仓库中自动处理与 issues 相关的标签，特别是当用户编辑他们的 issue 或评论时。它主要做以下几件事：

# 触发条件：当 issues 被编辑或者用户编辑了某个 issue 的评论时，脚本会被触发。

# 权限设置：需要 contents 读取权限来访问仓库内容，并且需要 issues 和 pull-requests 写入权限来更新 issue 和 PR 状态。

# 判断条件：如果某个 issue 是 打开状态（open），并且是由提交该 issue 的用户编辑的，脚本才会执行接下来的操作。

# 移除标签：脚本会自动移除两个标签：

# Inactive：用于标记不活跃的 issue。
# needs-more-info：用于标记需要更多信息的 issue。
name: Issue Remove Inactive

on:
  # issues:
  #   types: [edited]
  # issue_comment:
  #   types: [created, edited]
  issues:
    types: []
  issue_comment:
    types: []

permissions:
  contents: read

jobs:
  issue-remove-inactive:
    permissions:
      issues: write # for actions-cool/issues-helper to update issues
      pull-requests: write # for actions-cool/issues-helper to update PRs
    runs-on: ubuntu-latest
    steps:
      - name: remove inactive
        if: github.event.issue.state == 'open' && github.actor == github.event.issue.user.login
        uses: actions-cool/issues-helper@v3
        with:
          actions: remove-labels
          issue-number: ${{ github.event.issue.number }}
          labels: 'Inactive, needs-more-info'
